import 'package:pt_pro/model/member.dart';

final List<Member> members = [
  Member(
    id: '1',
    photoUrl: null,
    name: '김돌쇠',
    phone: '010-1234-5678',
    gender: Gender.male,
    birthDate: DateTime(1990, 5, 10),
    registrationDate: DateTime(2025, 7, 1),
    sessionStartDate: DateTime(2025, 7, 10),
    sessionEndDate: DateTime(2025, 8, 25),
    ptGoal: '다이어트',
    sessionCount: 10,
    currentSessionCount: 5,
    notes: '무릎 통증 있음',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Member(
    id: '2',
    photoUrl: null,
    name: '돌멩이',
    phone: '010-5678-1234',
    gender: Gender.female,
    birthDate: DateTime(1995, 3, 22),
    registrationDate: DateTime(2025, 7, 5),
    sessionStartDate: DateTime(2025, 7, 15),
    sessionEndDate: DateTime(2025, 9, 13),
    ptGoal: '체력 향상',
    sessionCount: 12,
    currentSessionCount: 4,
    notes: '어깨 긴장 있음',
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Member(
    id: '3',
    photoUrl: null,
    name: '김헬창',
    phone: '010-9999-8888',
    gender: Gender.male,
    birthDate: DateTime(1988, 11, 3),
    registrationDate: DateTime(2025, 7, 10),
    sessionStartDate: DateTime(2025, 7, 20),
    sessionEndDate: DateTime(2025, 9, 23),
    ptGoal: '벌크업',
    sessionCount: 15,
    currentSessionCount: 10,
    notes: null,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
];
